In [2]:
import pandas as pd
df = pd.DataFrame({
    'student name ': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'age': [20, 22, 19, 21, 23],
    'exam': ['passed', 'failed', 'passed', 'passed', 'failed'],
    'internet access': ['yes', 'no', 'yes', 'yes', 'no'],    
    'gender': ['female', 'male', 'male', 'male', 'female'],
    'presence': ['present', 'absent', 'present', 'present', 'absent'],
    'score' : [18, 8, 15, 13, 7],
    'study hours': [2, 1, 3, 4, 1]
    

})

In [2]:
df.tail(2)

    Name  Age Grade  Credits  GPA
8  David   31     C        2  2.7
9  Laura   29     A        3  3.5

In [3]:
filtered_df = df[df['Age'] > 30]
print(filtered_df)

      Name  Age Grade  Credits  GPA
2    Peter   35     C        2  2.9
3    Linda   32     A        3  3.7
6  Michael   40     A        3  3.9
8    David   31     C        2  2.7

In [6]:
df = df.sort_values(by='Name', ascending=True)
print(df)

      Name  Age Grade  Credits  GPA
1     Anna   24     B        4  3.2
8    David   31     C        2  2.7
5    Emily   27     C        2  2.8
4    James   30     B        4  3.1
0     John   28     A        3  3.8
9    Laura   29     A        3  3.5
3    Linda   32     A        3  3.7
6  Michael   40     A        3  3.9
2    Peter   35     C        2  2.9
7    Sarah   22     B        4  3.0

In [ ]:
df = df.rename(columns={'Name': 'Student Name' , 'Age': 'Student Age', 'Grade': 'Course Grade', 'Credits': 'Course Credits', 'GPA': 'Grade Point Average'})
print(df)

  Student Name  Student Age Course Grade  Course Credits  Grade Point Average
1         Anna           24            B               4                  3.2
8        David           31            C               2                  2.7
5        Emily           27            C               2                  2.8
4        James           30            B               4                  3.1
0         John           28            A               3                  3.8
9        Laura           29            A               3                  3.5
3        Linda           32            A               3                  3.7
6      Michael           40            A               3                  3.9
2        Peter           35            C               2                  2.9
7        Sarah           22            B               4                  3.0

In [20]:
df.tail()

  Student Name  Student Age Course Grade  Course Credits  Grade Point Average
9        Laura           29            A               3                  3.5
3        Linda           32            A               3                  3.7
6      Michael           40            A               3                  3.9
2        Peter           35            C               2                  2.9
7        Sarah           22            B               4                  3.0